name: Replace
description: Replace words
inputs:
  org:
    description: 'org'
    required: true
  env:
    description: 'env'
    required: true
  manifest:
    description: 'manifest'
    required: true
    
outputs:
  result:
    description: 'the file with the substituted words'

runs:
  using: 'node16'
  main: index.js
