name: Replace
description: Replace words
inputs:
  org:
    description: 'org'
    required: true
  env:
    description: 'env'
    required: true
  manifest:
    description: 'manifest'
    required: true
outputs:
  replacedData: ${{ steps.replacer.outputs.replacedData }}

runs:
  using: 'node12'
  main: index.js
