name: Replace
description: Replace words
inputs:
  org:
    description: 'org'
    required: true
  env:
    description: 'env'
    required: true
  manifest:
    description: 'manifest'
    required: true
    
runs:
  using: 'node12'
  main: index.js

# Add a step to capture the output
- name: Run index.js and capture output
  id: replace_output
  run: |
    output=$(node index.js)
    echo "::set-output name=replace_result::$output"