name: Replace
description: Replace words
inputs:
  org:
    description: 'org'
    required: true
  env:
    description: 'env'
    required: true
  manifest:
    description: 'manifest'
    required: true
    

runs:
  using: 'python'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Execute index.js
      run: |
        output=$(node index.js "${{ inputs.org }}" "${{ inputs.env }}" "${{ inputs.manifest }}")
        echo "::set-output name=result::$output"