name: CD

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push: 
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0

  deploy-to-aks: 
    name: Deploy to AKS
    runs-on: ubuntu-latest
    needs: build-and-push
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        org:
          - fintlabs-no
          - viken-no
          - visma-com
          - ude-oslo-kommune-no
          - innlandetfylke-no
          - agderfk-no
          - vlfk-no
          - mrfylke-no
          - vtfk-no
          - trondelagfylke-no
          - nfk-no
          - tffk-no
        cluster:
#          - aks-alpha-fint-2021-11-18
          - aks-beta-fint-2021-11-23
#          - aks-api-fint-2022-02-08
#          - aks-pwf-fint-2021-10-20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0

      - name: Get environment
        uses: actions/github-script@v6
        id: environment
        with:
          script: return '${{ matrix.cluster }}'.split('-')[1]
          result-encoding: string

      - name: Use Custom Action
        uses: FogadOg/githubWorkflowScriptTester@main
        id: replacer
        with:
          org: ${{ matrix.org }}
          env: ${{ steps.environment.outputs.result }}
          manifest: ${{ steps.bake.outputs.result }}
